import type { Metadata } from "next";
import "./globals.css";
import { MediaQuery } from "@/contexts";

export const metadata: Metadata = {
  title: "Space Tourism | Frontend mentor",
  description: "Generated by create next app",
  icons: "favicon-32x32.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MediaQuery>{children}</MediaQuery>
      </body>
    </html>
  );
}
